title: jekyll-garden
description: A jekyll theme for semantically inclined digital gardeners.
author: soumyak4
baseurl: '/jekyll-garden'
url: 'https://soumyak4.in'

include:
  - "_pages"
exclude:
  - "*.gemspec"
  - "*.gem"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "README.md"
  - "CHANGELOG"
  - "LICENSE"

# how to organize md files:
# 1. collections_dir: "docs"
#    from: https://jekyllrb.com/docs/collections/
# 2. also worth double checking... 
#     from: https://github.com/eritbh/jekyll-glob
collections:
  books:
    output: true
  entries:
    output: true
  index:
    output: true
  states:
    output: true
    order:
      - tags.md
      - sprout.md
      - bud.md
      - bamboo.md
      - bloom.md
      - berry.md
      - fruit.md
      - melon.md
      - seed.md
      - tea.md
      - pot-bamboo.md

# frontmatter
# ('type' is explicitly set for search exclusion to work)
defaults:
  - 
    scope:
      type: "pages"
    values:
      type: "pages"
  - 
    scope:
      # path: "_posts/**/*.md"
      type: "posts"
    values:
      type: "posts"
      layout: "post"
      permalink: "/post/:id/"
  - 
    scope:
      # path: "_books/**/*.md"
      type: "books"
    values:
      type: "books"
      layout: "book"
      permalink: "/book/:id/"
  - 
    scope:
      # path: "_entries/**/*.md"
      type: "entries"
    values:
      type: "entries"
      layout: "entry"
      permalink: "/entry/:id/"
  - 
    scope:
      # path: "_index/**/*.md"
      type: "index"
    values:
      type: "index"
      # layout: "index"
      # permalink: "/index/:id/"
  - 
    scope:
      # path: "_states/**/*.md"
      type: "states"
    values:
      type: "states"
      layout: "state"
      permalink: "/stat/:id/"

sass:
  sass_dir:          _sass
  style:            :compressed

enable_mathjax: true
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false 

# 
# plugins
# 

# Google Analytics (ip is anonymized by default)
# ga_tracking: UA-190413040-4

# seo
# tagline: ""
# description: ""
# twitter:
#   card: summary
#   username: manunamz
# author:
#   twitter: manunamz

# 
# plugins
# 

ids:
  # from: https://github.com/radeno/nanoid.rb#options
  format:
    alpha: '1234567890abcdef'
    size: 10
semtree:
  # enabled: true
  # root: 'i.bonsai'
  # doctype: 'index'
  virtual_trunk: true
  # exclude:
  #   - "books"
  #   - "pages"
  #   - "posts"
  #   - "states"
wikirefs:
  # enabled: true
  exclude:
    - "states"
  css:
    exclude:
      # markdown
      - "footnote"
      - "reversefootnote"
      # local-theme-related
      - "site-nav-btn"
      - "sem-tag"
      - "stat-tag"
      # includes
      - "anchor-heading"
      - "toc-list-item-anchor"
graph:
  # enabled: true
  # path:
  #   assets: "/assets"
  #   scripts: "/assets/js"
  exclude:
    - "books"
    - "index"
    - "pages"
    - "posts"
    - "states"
  tree:
    # enabled: true
    dag_lvl_dist: 100
    force:
      charge: -100
      strength_x: 0.3
      x_val: 0.9
      strength_y: 0.1
      y_val: 0.9
  web:
    # enabled: true
    # exclude:
    #   links: true
    force:
      charge: -300
      strength_x: 0.3
      x_val: 0.75
      strength_y: 0.1
      y_val: 0.9

# 
# includes
# 

social:
  connect:
    enabled: true
    url:
      # facebook:
      github: https://github.com/wikibonsai/jekyll-garden/
      # linkedin:
      # pinterest:
      # rss:
      # twitter:
  share:
    enabled: true
    type:
      - 'email'
      # - 'facebook'
      - 'linkedin'
      # - 'pinterest'
      - 'twitter'

# 
# bonsai template configs
# 

bonsai:
  debug: false
  default_theme: "light"
  date_format: "%Y-%m-%d"
  svg: 
    filter: false
    # smaller: false
  # site-nav
  nav:
    type: "graph"  # may be 'visited' (steps) or 'graph' (bonsai)
    graph:
      kind: "tree" # may be 'tree' or 'web'
    search:
      enabled: true
      exclude: []
    visited:
      enabled: true
  # pages
  home:
    notable:
      enabled: true
      docs:
        - bonsai.md
        - wiki-blog.md
        - feature.md
        - 2021-11-18-setup.md
        - 2021-05-11-origin-myth.md
    recent: 
      enabled: true
      cap: 5
  archive:
    section:
      posts: "🫐 🥭 🍈 Fruits"
      books: "🌰 🍵 🎍 Germs"
      entries: "🌱 🌿 🎋 🌸 Foliage"
  # map:
  recent:
    cap: 10
  # documents
  states:
    root_path: "_states/tags.md"
  entries:
    root_path: "_entries/jekyll-garden.md"
    toggles:  # may be 'open' or 'closed'
      breadcrumb: "open"
      attr_box: "open"
      foot_links: "open"
      foot_tagged: "open"
    backlinks: true
